### PR TITLE
Save PNGs as JPEGs so they don’t break

### LINKED ISSUE #15: PNGs with alpha channel fail to upload
RGB PNGs work fine but RGBA PNGs fail when PIL tries to save them as JPEG

### PR DESCRIPTION
**Pull request by felixbade**
fixes #15

### CODE REVIEW

**Comment by samporapeli** [comment]
This works on PNG images without alpha layer, but gives `OSError: cannot write mode RGBA as JPEG` for some PNGs.

**Comment by felixbade** [comment]
Made a new issue (#15) about the problem @samporapeli described

**Comment by felixbade** [comment]
fixes #15

**Comment by felixbade** [comment]
fixes #15

**Review by samporapeli — APPROVED** [review]

**Pull request merged**
