### PR TITLE
Feature/nav bar

### PR DESCRIPTION
**Pull request by felixbade**
This introduces UI changes towards #9.

### CODE REVIEW

**Comment by samporapeli** [comment]
Navbar is great! I'm slightly concernced about the code style here, is there anything we could do to avoid `!important`s for example? Is style something that we should focus currently this much to?

**Comment by felixbade** [comment]
We can omit the `!important` for example by adding more css classes so that we can get rid of the `.nav-item a` selector. I think it’s fine since the origin of the need is documented in the comment but you are right that it’s not optimal to use `!important`.

> Since he might not know exactly why those !important rules were added in the first place, he might opt for the second option for fear of breaking something somewhere else on the site he’s not aware of. And thus the vicious cycle starts.

https://css-tricks.com/when-using-important-is-the-right-choice/

Usually `!important` is used without documenting why (and I think thus the bad reputation) but that’s not the case here.

**Comment by felixbade** [comment]
We could remove the `!important` by making the `.nav-logo-link` selector more specific with additional tags. For example make it `div a.nav-logo-link`. I don’t know if that’s any cleaner but this article suggests it: https://techrangers.cdl.ucf.edu/2018/09/10/css-specificity.html

TBH I wish that CSS just treated `.class` as more specific than `.parent-class tag`, but that’s unfortunately out of our control.

**Comment by samporapeli** [comment]
Sounds good to me!

**Review by samporapeli — APPROVED** [review]
Awesome!

**Pull request merged**
